### ISSUE TITLE
CI/CD Automate the building of example images that can be done prior to releasing new version

### ISSUE THREAD

**Issue by jemcginn** [amalgam8/amalgam8#406] opened 2016-11-17 16:33 UTC
There are 3 related issues associated with the overall goal of being able to automate the release of new A8 versions.  Currently the sidecar, controller, and registry have automation in place.  The goal of this set of issues is to extend automation to the building, testing, and publishing of the examples that are associated with A8 (bookinfo and helloworld).    

Following are the manual steps that are occurring for each of the A8 releases).  

    1. Update changelog.
    2. Update Dockerhub images to install new release.
    3. Create interim release.
    4. Build bookinfo/helloworld app images.  
    5. Verify bookinfo/helloworld demo steps in K8S and Docker environments.
    6.  Make release public.
    7. Push bookinfo/helloworld images to Dockerhub.

When a git commit is tagged with a version for release (e.g., v0.4.3), we need to run the following tasks in automated fashion:

    1) Build bookinfo/helloworld app images using the latest version of sidecar in master, as opposed to the one in GitHub. [Look into docker args or docker compose build for this]
    2) Verify bookinfo/helloworld demo steps in K8S and Docker environments. [Reuse the a version of demo_script.sh from this commit 659dc19e82c5b179c9159b176affcb085841448e]
    3) push docker images for the example images for bookinfo and helloworld. [We already have a mechanism in place to push docker images for a8-controller,registry and sidecar

This issue will focus on step 4, Build bookinfo/helloworld app images.

https://github.com/amalgam8/amalgam8/issues/405  will focus on step 5 (automated testing)

https://github.com/amalgam8/amalgam8/issues/404 will focus on step 7 (automated publishing of the bookinfo/helloworld images to Dockerhub).

**Comment by ijsnellf** [comment] 2016-11-17 16:59
Right now I perform the following manual steps for each A8 release (most relevant portion in **bold**):

 1. Update changelog.
 1. Update Dockerhub images to install new release.
 1. Create interim release.
 1. **Build bookinfo/helloworld app images.**
 1. Verify bookinfo/helloworld demo steps in K8S and Docker environments.
 1. Make release public.
 1. Push bookinfo/helloworld images to Dockerhub.

**Comment by rshriram** [comment] 2016-11-17 19:57
closing as duplicate of #404

**Comment by jemcginn** [comment] 2016-11-17 20:06
We would like to treat the automation associated with delivering new versions as several separate items so that we can have distinct notes/discussion about each of these items.  The overall functionality can be delivered in stages thus wanting to keep these issues separate.  Reopening this issue.

**Comment by craigyam** [comment] 2017-01-20 15:54
Addressed by PR #467

**Closed as completed by craigyam** 2017-01-20 15:54 UTC
Labels: examples
